### PR TITLE
Removed tab at header include that was causing header file to not load. ...

### PR DESCRIPTION
**Pull request by TerrordactylDesigns**
...Converted doctype to stop deprecation error. Main page of app now loads again.

### CODE REVIEW

**Comment by TerrordactylDesigns** [comment]
Hey man, following your tutorial and ran into some snags on the first run of the app. There was an tab in the include file that was being viewed as non utf-8 and was throwing errors. Once that was cleared the page still didn't render because Jade deprecated the !!! 5 tag. Base page loads with these fixed.

**Comment by mysterycommand** [comment]
I was about to create this same pull request. +1

**Comment by MattCowski** [comment]
Thank you!

**Comment by tommillard** [comment]
Had the same problem with the jade files. This changed fixed the issue, thanks.

**Pull request merged**
